alias addall='git add -N . && git add -p'
alias addup='git add -p'
alias branch='git branch'
alias checkout='git checkout'
alias clone='git clone'
alias fetch='git fetch'
alias pull='git pull origin'
alias tag='git tag'
alias newtag='git tag -a'
alias gs='git status'
alias myhash='git rev-parse HEAD | pbcopy'
# poor man repo
# alias repo='open (git config --get remote.origin.url)'
alias lg='lazygit'
alias gstash='git stash push -m'
alias gtags='git tag -l | sort -V'

# github cli 
alias repo='gh repo view --web'
alias draftPR='gh pr create --fill -d'
alias mypr='gh pr view --web'
alias checkPR='gh pr checkout '
